"""update expirty field

Revision ID: 1714495079
Revises: 1714495017
Create Date: 2024-04-30 18:37:59.542444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1714495079'
down_revision: Union[str, None] = '1714495017'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code_expiry', sa.DateTime(), nullable=True))
    op.drop_column('users', 'verification_code_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'verification_code_expiry')
    # ### end Alembic commands ###
